//! Zsh initialization script generation.
//!
//! Produces a zsh script that, when eval'd, sets up capsule prompt integration:
//! coproc relay, precmd/preexec hooks, and async update handling.

/// Generate the zsh initialization script.
///
/// The returned script is intended to be eval'd in the user's `.zshrc`:
///
/// ```zsh
/// eval "$(capsule init zsh)"
/// ```
#[must_use]
pub const fn generate() -> &'static str {
    include_str!("init.zsh")
}

/// Generate the zsh initialization script for local coprocess mode.
///
/// The returned script starts `capsule connect --local` instead of the
/// daemon-backed `capsule connect` relay:
///
/// ```zsh
/// eval "$(capsule init zsh --local)"
/// ```
#[must_use]
pub fn generate_local() -> String {
    generate_local_with_connect_command("capsule")
}

/// Generate the zsh initialization script for local coprocess mode with an
/// explicit `capsule` command path.
///
/// `connect_command` must be a shell-safe single word.
#[must_use]
pub fn generate_local_with_connect_command(connect_command: &str) -> String {
    generate().replace(
        "coproc command capsule connect 2>/dev/null",
        &format!("coproc command {connect_command} connect --local 2>/dev/null"),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn contains_fallback_prompt() {
        let script = generate();
        assert!(
            script.contains("%F{green}%n%f@%m %F{green}%~%f %# "),
            "missing fallback prompt"
        );
    }

    #[test]
    fn sets_prompt() {
        let script = generate();
        assert!(script.contains("PROMPT="), "script should set PROMPT");
    }

    #[test]
    fn sets_right_prompt() {
        let script = generate();
        assert!(
            script.contains("RPROMPT=$_CAPSULE_RIGHT2"),
            "script should set RPROMPT from prompt metadata"
        );
    }

    #[test]
    fn does_not_add_blank_line_before_prompt() {
        let script = generate();
        assert!(
            !script.contains("# Match Starship's default add_newline behavior.\n    print"),
            "script should not print a blank line before each prompt"
        );
    }

    #[test]
    fn registers_hooks() {
        let script = generate();
        assert!(
            script.contains("precmd_functions"),
            "should register precmd hook"
        );
        assert!(
            script.contains("preexec_functions"),
            "should register preexec hook"
        );
        assert!(
            script.contains("zshexit_functions"),
            "should register zshexit hook"
        );
    }

    #[test]
    fn calls_capsule_connect() {
        let script = generate();
        assert!(
            script.contains("capsule connect"),
            "coproc should run capsule connect"
        );
    }

    #[test]
    fn local_mode_calls_capsule_connect_local() {
        let script = generate_local();
        assert!(
            script.contains("capsule connect --local"),
            "local coproc should run capsule connect --local"
        );
    }

    #[test]
    fn local_mode_uses_explicit_connect_command() {
        let script = generate_local_with_connect_command("'/nix/store/example/bin/capsule'");
        assert!(
            script.contains("coproc command '/nix/store/example/bin/capsule' connect --local"),
            "local coproc should use explicit connect command"
        );
    }

    #[test]
    fn session_id_managed_by_connect() {
        let script = generate();
        // Session ID is now generated by capsule connect, not the shell
        assert!(
            !script.contains("_CAPSULE_SESSION_ID"),
            "session ID should not be in shell script (managed by connect)"
        );
        assert!(
            !script.contains("/dev/urandom"),
            "shell should not read /dev/urandom (connect does it)"
        );
    }

    #[test]
    fn no_function_defs_after_init() {
        let script = generate();
        let marker = "\n_capsule_init\n";
        assert!(script.contains(marker), "script should call _capsule_init");
        let (_, after_init) = script.split_once(marker).unwrap_or(("", ""));
        assert!(
            !after_init.contains("() {"),
            "no function definitions should appear after _capsule_init"
        );
    }

    #[test]
    fn suppresses_running_jobs_warning() {
        let script = generate();
        assert!(
            script.contains("setopt NO_CHECK_RUNNING_JOBS"),
            "should suppress running-job exit warnings for capsule's coproc"
        );
        assert!(
            script.contains("disown %+"),
            "should remove capsule coproc from the zsh job table"
        );
    }

    #[test]
    fn exports_stale_fds_for_exec_cleanup() {
        let script = generate();
        // zsh does not set close-on-exec on {var} file descriptors, so
        // we export the FD numbers to let the next shell instance close
        // them after exec replaces the process.
        assert!(
            script.contains("export _CAPSULE_STALE_FDS"),
            "should export stale FD numbers for post-exec cleanup"
        );
        assert!(
            script.contains("unset _CAPSULE_STALE_FDS"),
            "should unset stale FDs after cleanup"
        );
    }
}
